project_id = "nnvllbxleujvqoyfqgqe"

[functions.validate-access-code]
verify_jwt = false

[functions.test-integration]
verify_jwt = true

[functions.update-secrets]
verify_jwt = true

[functions.twilio-voice]
verify_jwt = false
